// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface BatchUpdateBlobsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The responses to the requests.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.Response responses = 1;</code>
   */
  java.util.List<com.google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.Response> 
      getResponsesList();
  /**
   * <pre>
   * The responses to the requests.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.Response responses = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.Response getResponses(int index);
  /**
   * <pre>
   * The responses to the requests.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.Response responses = 1;</code>
   */
  int getResponsesCount();
  /**
   * <pre>
   * The responses to the requests.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.Response responses = 1;</code>
   */
  java.util.List<? extends com.google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.ResponseOrBuilder> 
      getResponsesOrBuilderList();
  /**
   * <pre>
   * The responses to the requests.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.Response responses = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.BatchUpdateBlobsResponse.ResponseOrBuilder getResponsesOrBuilder(
      int index);
}
