// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface DirectoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.Directory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The files in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.FileNode files = 1;</code>
   */
  java.util.List<com.google.devtools.remoteexecution.v1test.FileNode> 
      getFilesList();
  /**
   * <pre>
   * The files in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.FileNode files = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.FileNode getFiles(int index);
  /**
   * <pre>
   * The files in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.FileNode files = 1;</code>
   */
  int getFilesCount();
  /**
   * <pre>
   * The files in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.FileNode files = 1;</code>
   */
  java.util.List<? extends com.google.devtools.remoteexecution.v1test.FileNodeOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <pre>
   * The files in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.FileNode files = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.FileNodeOrBuilder getFilesOrBuilder(
      int index);

  /**
   * <pre>
   * The subdirectories in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.DirectoryNode directories = 2;</code>
   */
  java.util.List<com.google.devtools.remoteexecution.v1test.DirectoryNode> 
      getDirectoriesList();
  /**
   * <pre>
   * The subdirectories in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.DirectoryNode directories = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.DirectoryNode getDirectories(int index);
  /**
   * <pre>
   * The subdirectories in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.DirectoryNode directories = 2;</code>
   */
  int getDirectoriesCount();
  /**
   * <pre>
   * The subdirectories in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.DirectoryNode directories = 2;</code>
   */
  java.util.List<? extends com.google.devtools.remoteexecution.v1test.DirectoryNodeOrBuilder> 
      getDirectoriesOrBuilderList();
  /**
   * <pre>
   * The subdirectories in the directory.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.DirectoryNode directories = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.DirectoryNodeOrBuilder getDirectoriesOrBuilder(
      int index);
}
