// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface FindMissingBlobsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.FindMissingBlobsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of the blobs requested *not* present in the storage.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Digest missing_blob_digests = 2;</code>
   */
  java.util.List<com.google.devtools.remoteexecution.v1test.Digest> 
      getMissingBlobDigestsList();
  /**
   * <pre>
   * A list of the blobs requested *not* present in the storage.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Digest missing_blob_digests = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.Digest getMissingBlobDigests(int index);
  /**
   * <pre>
   * A list of the blobs requested *not* present in the storage.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Digest missing_blob_digests = 2;</code>
   */
  int getMissingBlobDigestsCount();
  /**
   * <pre>
   * A list of the blobs requested *not* present in the storage.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Digest missing_blob_digests = 2;</code>
   */
  java.util.List<? extends com.google.devtools.remoteexecution.v1test.DigestOrBuilder> 
      getMissingBlobDigestsOrBuilderList();
  /**
   * <pre>
   * A list of the blobs requested *not* present in the storage.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Digest missing_blob_digests = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.DigestOrBuilder getMissingBlobDigestsOrBuilder(
      int index);
}
