// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface GetTreeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.GetTreeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  java.util.List<com.google.devtools.remoteexecution.v1test.Directory> 
      getDirectoriesList();
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.Directory getDirectories(int index);
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  int getDirectoriesCount();
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  java.util.List<? extends com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> 
      getDirectoriesOrBuilderList();
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder getDirectoriesOrBuilder(
      int index);

  /**
   * <pre>
   * If present, signifies that there are more results which the client can
   * retrieve by passing this as the page_token in a subsequent
   * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
   * If empty, signifies that this is the last page of results.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * If present, signifies that there are more results which the client can
   * retrieve by passing this as the page_token in a subsequent
   * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
   * If empty, signifies that this is the last page of results.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
