// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

/**
 * <pre>
 * A response message for
 * [ContentAddressableStorage.GetTree][google.devtools.remoteexecution.v1test.ContentAddressableStorage.GetTree].
 * This message is deprecated and should no longer be used.
 * </pre>
 *
 * Protobuf type {@code google.devtools.remoteexecution.v1test.GetTreeResponse}
 */
public  final class GetTreeResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.devtools.remoteexecution.v1test.GetTreeResponse)
    GetTreeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTreeResponse.newBuilder() to construct.
  private GetTreeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTreeResponse() {
    directories_ = java.util.Collections.emptyList();
    nextPageToken_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTreeResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              directories_ = new java.util.ArrayList<com.google.devtools.remoteexecution.v1test.Directory>();
              mutable_bitField0_ |= 0x00000001;
            }
            directories_.add(
                input.readMessage(com.google.devtools.remoteexecution.v1test.Directory.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            nextPageToken_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        directories_ = java.util.Collections.unmodifiableList(directories_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.remoteexecution.v1test.GetTreeResponse.class, com.google.devtools.remoteexecution.v1test.GetTreeResponse.Builder.class);
  }

  private int bitField0_;
  public static final int DIRECTORIES_FIELD_NUMBER = 1;
  private java.util.List<com.google.devtools.remoteexecution.v1test.Directory> directories_;
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  public java.util.List<com.google.devtools.remoteexecution.v1test.Directory> getDirectoriesList() {
    return directories_;
  }
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  public java.util.List<? extends com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> 
      getDirectoriesOrBuilderList() {
    return directories_;
  }
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  public int getDirectoriesCount() {
    return directories_.size();
  }
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  public com.google.devtools.remoteexecution.v1test.Directory getDirectories(int index) {
    return directories_.get(index);
  }
  /**
   * <pre>
   * The directories descended from the requested root.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
   */
  public com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder getDirectoriesOrBuilder(
      int index) {
    return directories_.get(index);
  }

  public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2;
  private volatile java.lang.Object nextPageToken_;
  /**
   * <pre>
   * If present, signifies that there are more results which the client can
   * retrieve by passing this as the page_token in a subsequent
   * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
   * If empty, signifies that this is the last page of results.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   */
  public java.lang.String getNextPageToken() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nextPageToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * If present, signifies that there are more results which the client can
   * retrieve by passing this as the page_token in a subsequent
   * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
   * If empty, signifies that this is the last page of results.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNextPageTokenBytes() {
    java.lang.Object ref = nextPageToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nextPageToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < directories_.size(); i++) {
      output.writeMessage(1, directories_.get(i));
    }
    if (!getNextPageTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nextPageToken_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < directories_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, directories_.get(i));
    }
    if (!getNextPageTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nextPageToken_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.remoteexecution.v1test.GetTreeResponse)) {
      return super.equals(obj);
    }
    com.google.devtools.remoteexecution.v1test.GetTreeResponse other = (com.google.devtools.remoteexecution.v1test.GetTreeResponse) obj;

    boolean result = true;
    result = result && getDirectoriesList()
        .equals(other.getDirectoriesList());
    result = result && getNextPageToken()
        .equals(other.getNextPageToken());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDirectoriesCount() > 0) {
      hash = (37 * hash) + DIRECTORIES_FIELD_NUMBER;
      hash = (53 * hash) + getDirectoriesList().hashCode();
    }
    hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getNextPageToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.remoteexecution.v1test.GetTreeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A response message for
   * [ContentAddressableStorage.GetTree][google.devtools.remoteexecution.v1test.ContentAddressableStorage.GetTree].
   * This message is deprecated and should no longer be used.
   * </pre>
   *
   * Protobuf type {@code google.devtools.remoteexecution.v1test.GetTreeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.devtools.remoteexecution.v1test.GetTreeResponse)
      com.google.devtools.remoteexecution.v1test.GetTreeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.remoteexecution.v1test.GetTreeResponse.class, com.google.devtools.remoteexecution.v1test.GetTreeResponse.Builder.class);
    }

    // Construct using com.google.devtools.remoteexecution.v1test.GetTreeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDirectoriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (directoriesBuilder_ == null) {
        directories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        directoriesBuilder_.clear();
      }
      nextPageToken_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_descriptor;
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.GetTreeResponse getDefaultInstanceForType() {
      return com.google.devtools.remoteexecution.v1test.GetTreeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.GetTreeResponse build() {
      com.google.devtools.remoteexecution.v1test.GetTreeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.GetTreeResponse buildPartial() {
      com.google.devtools.remoteexecution.v1test.GetTreeResponse result = new com.google.devtools.remoteexecution.v1test.GetTreeResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (directoriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          directories_ = java.util.Collections.unmodifiableList(directories_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.directories_ = directories_;
      } else {
        result.directories_ = directoriesBuilder_.build();
      }
      result.nextPageToken_ = nextPageToken_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.remoteexecution.v1test.GetTreeResponse) {
        return mergeFrom((com.google.devtools.remoteexecution.v1test.GetTreeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.remoteexecution.v1test.GetTreeResponse other) {
      if (other == com.google.devtools.remoteexecution.v1test.GetTreeResponse.getDefaultInstance()) return this;
      if (directoriesBuilder_ == null) {
        if (!other.directories_.isEmpty()) {
          if (directories_.isEmpty()) {
            directories_ = other.directories_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDirectoriesIsMutable();
            directories_.addAll(other.directories_);
          }
          onChanged();
        }
      } else {
        if (!other.directories_.isEmpty()) {
          if (directoriesBuilder_.isEmpty()) {
            directoriesBuilder_.dispose();
            directoriesBuilder_ = null;
            directories_ = other.directories_;
            bitField0_ = (bitField0_ & ~0x00000001);
            directoriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDirectoriesFieldBuilder() : null;
          } else {
            directoriesBuilder_.addAllMessages(other.directories_);
          }
        }
      }
      if (!other.getNextPageToken().isEmpty()) {
        nextPageToken_ = other.nextPageToken_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.devtools.remoteexecution.v1test.GetTreeResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.devtools.remoteexecution.v1test.GetTreeResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.google.devtools.remoteexecution.v1test.Directory> directories_ =
      java.util.Collections.emptyList();
    private void ensureDirectoriesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        directories_ = new java.util.ArrayList<com.google.devtools.remoteexecution.v1test.Directory>(directories_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> directoriesBuilder_;

    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public java.util.List<com.google.devtools.remoteexecution.v1test.Directory> getDirectoriesList() {
      if (directoriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(directories_);
      } else {
        return directoriesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public int getDirectoriesCount() {
      if (directoriesBuilder_ == null) {
        return directories_.size();
      } else {
        return directoriesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory getDirectories(int index) {
      if (directoriesBuilder_ == null) {
        return directories_.get(index);
      } else {
        return directoriesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder setDirectories(
        int index, com.google.devtools.remoteexecution.v1test.Directory value) {
      if (directoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDirectoriesIsMutable();
        directories_.set(index, value);
        onChanged();
      } else {
        directoriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder setDirectories(
        int index, com.google.devtools.remoteexecution.v1test.Directory.Builder builderForValue) {
      if (directoriesBuilder_ == null) {
        ensureDirectoriesIsMutable();
        directories_.set(index, builderForValue.build());
        onChanged();
      } else {
        directoriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder addDirectories(com.google.devtools.remoteexecution.v1test.Directory value) {
      if (directoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDirectoriesIsMutable();
        directories_.add(value);
        onChanged();
      } else {
        directoriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder addDirectories(
        int index, com.google.devtools.remoteexecution.v1test.Directory value) {
      if (directoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDirectoriesIsMutable();
        directories_.add(index, value);
        onChanged();
      } else {
        directoriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder addDirectories(
        com.google.devtools.remoteexecution.v1test.Directory.Builder builderForValue) {
      if (directoriesBuilder_ == null) {
        ensureDirectoriesIsMutable();
        directories_.add(builderForValue.build());
        onChanged();
      } else {
        directoriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder addDirectories(
        int index, com.google.devtools.remoteexecution.v1test.Directory.Builder builderForValue) {
      if (directoriesBuilder_ == null) {
        ensureDirectoriesIsMutable();
        directories_.add(index, builderForValue.build());
        onChanged();
      } else {
        directoriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder addAllDirectories(
        java.lang.Iterable<? extends com.google.devtools.remoteexecution.v1test.Directory> values) {
      if (directoriesBuilder_ == null) {
        ensureDirectoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, directories_);
        onChanged();
      } else {
        directoriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder clearDirectories() {
      if (directoriesBuilder_ == null) {
        directories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        directoriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public Builder removeDirectories(int index) {
      if (directoriesBuilder_ == null) {
        ensureDirectoriesIsMutable();
        directories_.remove(index);
        onChanged();
      } else {
        directoriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory.Builder getDirectoriesBuilder(
        int index) {
      return getDirectoriesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder getDirectoriesOrBuilder(
        int index) {
      if (directoriesBuilder_ == null) {
        return directories_.get(index);  } else {
        return directoriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public java.util.List<? extends com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> 
         getDirectoriesOrBuilderList() {
      if (directoriesBuilder_ != null) {
        return directoriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(directories_);
      }
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory.Builder addDirectoriesBuilder() {
      return getDirectoriesFieldBuilder().addBuilder(
          com.google.devtools.remoteexecution.v1test.Directory.getDefaultInstance());
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Directory.Builder addDirectoriesBuilder(
        int index) {
      return getDirectoriesFieldBuilder().addBuilder(
          index, com.google.devtools.remoteexecution.v1test.Directory.getDefaultInstance());
    }
    /**
     * <pre>
     * The directories descended from the requested root.
     * </pre>
     *
     * <code>repeated .google.devtools.remoteexecution.v1test.Directory directories = 1;</code>
     */
    public java.util.List<com.google.devtools.remoteexecution.v1test.Directory.Builder> 
         getDirectoriesBuilderList() {
      return getDirectoriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder> 
        getDirectoriesFieldBuilder() {
      if (directoriesBuilder_ == null) {
        directoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.devtools.remoteexecution.v1test.Directory, com.google.devtools.remoteexecution.v1test.Directory.Builder, com.google.devtools.remoteexecution.v1test.DirectoryOrBuilder>(
                directories_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        directories_ = null;
      }
      return directoriesBuilder_;
    }

    private java.lang.Object nextPageToken_ = "";
    /**
     * <pre>
     * If present, signifies that there are more results which the client can
     * retrieve by passing this as the page_token in a subsequent
     * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
     * If empty, signifies that this is the last page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public java.lang.String getNextPageToken() {
      java.lang.Object ref = nextPageToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nextPageToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * If present, signifies that there are more results which the client can
     * retrieve by passing this as the page_token in a subsequent
     * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
     * If empty, signifies that this is the last page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNextPageTokenBytes() {
      java.lang.Object ref = nextPageToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nextPageToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * If present, signifies that there are more results which the client can
     * retrieve by passing this as the page_token in a subsequent
     * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
     * If empty, signifies that this is the last page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public Builder setNextPageToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nextPageToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If present, signifies that there are more results which the client can
     * retrieve by passing this as the page_token in a subsequent
     * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
     * If empty, signifies that this is the last page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public Builder clearNextPageToken() {
      
      nextPageToken_ = getDefaultInstance().getNextPageToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If present, signifies that there are more results which the client can
     * retrieve by passing this as the page_token in a subsequent
     * [request][google.devtools.remoteexecution.v1test.GetTreeRequest].
     * If empty, signifies that this is the last page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     */
    public Builder setNextPageTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nextPageToken_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.devtools.remoteexecution.v1test.GetTreeResponse)
  }

  // @@protoc_insertion_point(class_scope:google.devtools.remoteexecution.v1test.GetTreeResponse)
  private static final com.google.devtools.remoteexecution.v1test.GetTreeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.remoteexecution.v1test.GetTreeResponse();
  }

  public static com.google.devtools.remoteexecution.v1test.GetTreeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTreeResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetTreeResponse>() {
    @java.lang.Override
    public GetTreeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTreeResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTreeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTreeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.GetTreeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

