// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface OutputFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.OutputFile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The full path of the file relative to the input root, including the
   * filename. The path separator is a forward slash `/`.
   * </pre>
   *
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <pre>
   * The full path of the file relative to the input root, including the
   * filename. The path separator is a forward slash `/`.
   * </pre>
   *
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   * The digest of the file's content.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  boolean hasDigest();
  /**
   * <pre>
   * The digest of the file's content.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.Digest getDigest();
  /**
   * <pre>
   * The digest of the file's content.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.DigestOrBuilder getDigestOrBuilder();

  /**
   * <pre>
   * The raw content of the file.
   * This field may be used by the server to provide the content of a file
   * inline in an
   * [ActionResult][google.devtools.remoteexecution.v1test.ActionResult] and
   * avoid requiring that the client make a separate call to
   * [ContentAddressableStorage.GetBlob] to retrieve it.
   * The client SHOULD NOT assume that it will get raw content with any request,
   * and always be prepared to retrieve it via `digest`.
   * </pre>
   *
   * <code>bytes content = 3;</code>
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <pre>
   * True if file is executable, false otherwise.
   * </pre>
   *
   * <code>bool is_executable = 4;</code>
   */
  boolean getIsExecutable();
}
