// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

/**
 * <pre>
 * An `OutputDirectory` is the output in an `ActionResult` corresponding to a
 * directory's full contents rather than a single file.
 * </pre>
 *
 * Protobuf type {@code google.devtools.remoteexecution.v1test.OutputDirectory}
 */
public  final class OutputDirectory extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.devtools.remoteexecution.v1test.OutputDirectory)
    OutputDirectoryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OutputDirectory.newBuilder() to construct.
  private OutputDirectory(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OutputDirectory() {
    path_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OutputDirectory(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            path_ = s;
            break;
          }
          case 18: {
            com.google.devtools.remoteexecution.v1test.Digest.Builder subBuilder = null;
            if (digest_ != null) {
              subBuilder = digest_.toBuilder();
            }
            digest_ = input.readMessage(com.google.devtools.remoteexecution.v1test.Digest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(digest_);
              digest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.devtools.remoteexecution.v1test.Digest.Builder subBuilder = null;
            if (treeDigest_ != null) {
              subBuilder = treeDigest_.toBuilder();
            }
            treeDigest_ = input.readMessage(com.google.devtools.remoteexecution.v1test.Digest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(treeDigest_);
              treeDigest_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.devtools.remoteexecution.v1test.OutputDirectory.class, com.google.devtools.remoteexecution.v1test.OutputDirectory.Builder.class);
  }

  public static final int PATH_FIELD_NUMBER = 1;
  private volatile java.lang.Object path_;
  /**
   * <pre>
   * The full path of the directory relative to the input root, including the
   * filename. The path separator is a forward slash `/`.
   * </pre>
   *
   * <code>string path = 1;</code>
   */
  public java.lang.String getPath() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      path_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The full path of the directory relative to the input root, including the
   * filename. The path separator is a forward slash `/`.
   * </pre>
   *
   * <code>string path = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPathBytes() {
    java.lang.Object ref = path_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      path_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DIGEST_FIELD_NUMBER = 2;
  private com.google.devtools.remoteexecution.v1test.Digest digest_;
  /**
   * <pre>
   * DEPRECATED: This field is deprecated and should no longer be used.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  public boolean hasDigest() {
    return digest_ != null;
  }
  /**
   * <pre>
   * DEPRECATED: This field is deprecated and should no longer be used.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  public com.google.devtools.remoteexecution.v1test.Digest getDigest() {
    return digest_ == null ? com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : digest_;
  }
  /**
   * <pre>
   * DEPRECATED: This field is deprecated and should no longer be used.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
   */
  public com.google.devtools.remoteexecution.v1test.DigestOrBuilder getDigestOrBuilder() {
    return getDigest();
  }

  public static final int TREE_DIGEST_FIELD_NUMBER = 3;
  private com.google.devtools.remoteexecution.v1test.Digest treeDigest_;
  /**
   * <pre>
   * The digest of the encoded
   * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
   * directory's contents.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
   */
  public boolean hasTreeDigest() {
    return treeDigest_ != null;
  }
  /**
   * <pre>
   * The digest of the encoded
   * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
   * directory's contents.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
   */
  public com.google.devtools.remoteexecution.v1test.Digest getTreeDigest() {
    return treeDigest_ == null ? com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : treeDigest_;
  }
  /**
   * <pre>
   * The digest of the encoded
   * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
   * directory's contents.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
   */
  public com.google.devtools.remoteexecution.v1test.DigestOrBuilder getTreeDigestOrBuilder() {
    return getTreeDigest();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPathBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, path_);
    }
    if (digest_ != null) {
      output.writeMessage(2, getDigest());
    }
    if (treeDigest_ != null) {
      output.writeMessage(3, getTreeDigest());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPathBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, path_);
    }
    if (digest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDigest());
    }
    if (treeDigest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTreeDigest());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.devtools.remoteexecution.v1test.OutputDirectory)) {
      return super.equals(obj);
    }
    com.google.devtools.remoteexecution.v1test.OutputDirectory other = (com.google.devtools.remoteexecution.v1test.OutputDirectory) obj;

    boolean result = true;
    result = result && getPath()
        .equals(other.getPath());
    result = result && (hasDigest() == other.hasDigest());
    if (hasDigest()) {
      result = result && getDigest()
          .equals(other.getDigest());
    }
    result = result && (hasTreeDigest() == other.hasTreeDigest());
    if (hasTreeDigest()) {
      result = result && getTreeDigest()
          .equals(other.getTreeDigest());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PATH_FIELD_NUMBER;
    hash = (53 * hash) + getPath().hashCode();
    if (hasDigest()) {
      hash = (37 * hash) + DIGEST_FIELD_NUMBER;
      hash = (53 * hash) + getDigest().hashCode();
    }
    if (hasTreeDigest()) {
      hash = (37 * hash) + TREE_DIGEST_FIELD_NUMBER;
      hash = (53 * hash) + getTreeDigest().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.devtools.remoteexecution.v1test.OutputDirectory parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.devtools.remoteexecution.v1test.OutputDirectory prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * An `OutputDirectory` is the output in an `ActionResult` corresponding to a
   * directory's full contents rather than a single file.
   * </pre>
   *
   * Protobuf type {@code google.devtools.remoteexecution.v1test.OutputDirectory}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.devtools.remoteexecution.v1test.OutputDirectory)
      com.google.devtools.remoteexecution.v1test.OutputDirectoryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.devtools.remoteexecution.v1test.OutputDirectory.class, com.google.devtools.remoteexecution.v1test.OutputDirectory.Builder.class);
    }

    // Construct using com.google.devtools.remoteexecution.v1test.OutputDirectory.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      path_ = "";

      if (digestBuilder_ == null) {
        digest_ = null;
      } else {
        digest_ = null;
        digestBuilder_ = null;
      }
      if (treeDigestBuilder_ == null) {
        treeDigest_ = null;
      } else {
        treeDigest_ = null;
        treeDigestBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.devtools.remoteexecution.v1test.RemoteExecutionProto.internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_descriptor;
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.OutputDirectory getDefaultInstanceForType() {
      return com.google.devtools.remoteexecution.v1test.OutputDirectory.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.OutputDirectory build() {
      com.google.devtools.remoteexecution.v1test.OutputDirectory result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.devtools.remoteexecution.v1test.OutputDirectory buildPartial() {
      com.google.devtools.remoteexecution.v1test.OutputDirectory result = new com.google.devtools.remoteexecution.v1test.OutputDirectory(this);
      result.path_ = path_;
      if (digestBuilder_ == null) {
        result.digest_ = digest_;
      } else {
        result.digest_ = digestBuilder_.build();
      }
      if (treeDigestBuilder_ == null) {
        result.treeDigest_ = treeDigest_;
      } else {
        result.treeDigest_ = treeDigestBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.devtools.remoteexecution.v1test.OutputDirectory) {
        return mergeFrom((com.google.devtools.remoteexecution.v1test.OutputDirectory)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.devtools.remoteexecution.v1test.OutputDirectory other) {
      if (other == com.google.devtools.remoteexecution.v1test.OutputDirectory.getDefaultInstance()) return this;
      if (!other.getPath().isEmpty()) {
        path_ = other.path_;
        onChanged();
      }
      if (other.hasDigest()) {
        mergeDigest(other.getDigest());
      }
      if (other.hasTreeDigest()) {
        mergeTreeDigest(other.getTreeDigest());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.devtools.remoteexecution.v1test.OutputDirectory parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.devtools.remoteexecution.v1test.OutputDirectory) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object path_ = "";
    /**
     * <pre>
     * The full path of the directory relative to the input root, including the
     * filename. The path separator is a forward slash `/`.
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The full path of the directory relative to the input root, including the
     * filename. The path separator is a forward slash `/`.
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The full path of the directory relative to the input root, including the
     * filename. The path separator is a forward slash `/`.
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public Builder setPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      path_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The full path of the directory relative to the input root, including the
     * filename. The path separator is a forward slash `/`.
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public Builder clearPath() {
      
      path_ = getDefaultInstance().getPath();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The full path of the directory relative to the input root, including the
     * filename. The path separator is a forward slash `/`.
     * </pre>
     *
     * <code>string path = 1;</code>
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      path_ = value;
      onChanged();
      return this;
    }

    private com.google.devtools.remoteexecution.v1test.Digest digest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder> digestBuilder_;
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    public boolean hasDigest() {
      return digestBuilder_ != null || digest_ != null;
    }
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Digest getDigest() {
      if (digestBuilder_ == null) {
        return digest_ == null ? com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : digest_;
      } else {
        return digestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    public Builder setDigest(com.google.devtools.remoteexecution.v1test.Digest value) {
      if (digestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        digest_ = value;
        onChanged();
      } else {
        digestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    public Builder setDigest(
        com.google.devtools.remoteexecution.v1test.Digest.Builder builderForValue) {
      if (digestBuilder_ == null) {
        digest_ = builderForValue.build();
        onChanged();
      } else {
        digestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    public Builder mergeDigest(com.google.devtools.remoteexecution.v1test.Digest value) {
      if (digestBuilder_ == null) {
        if (digest_ != null) {
          digest_ =
            com.google.devtools.remoteexecution.v1test.Digest.newBuilder(digest_).mergeFrom(value).buildPartial();
        } else {
          digest_ = value;
        }
        onChanged();
      } else {
        digestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    public Builder clearDigest() {
      if (digestBuilder_ == null) {
        digest_ = null;
        onChanged();
      } else {
        digest_ = null;
        digestBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Digest.Builder getDigestBuilder() {
      
      onChanged();
      return getDigestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    public com.google.devtools.remoteexecution.v1test.DigestOrBuilder getDigestOrBuilder() {
      if (digestBuilder_ != null) {
        return digestBuilder_.getMessageOrBuilder();
      } else {
        return digest_ == null ?
            com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : digest_;
      }
    }
    /**
     * <pre>
     * DEPRECATED: This field is deprecated and should no longer be used.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest digest = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder> 
        getDigestFieldBuilder() {
      if (digestBuilder_ == null) {
        digestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder>(
                getDigest(),
                getParentForChildren(),
                isClean());
        digest_ = null;
      }
      return digestBuilder_;
    }

    private com.google.devtools.remoteexecution.v1test.Digest treeDigest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder> treeDigestBuilder_;
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    public boolean hasTreeDigest() {
      return treeDigestBuilder_ != null || treeDigest_ != null;
    }
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Digest getTreeDigest() {
      if (treeDigestBuilder_ == null) {
        return treeDigest_ == null ? com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : treeDigest_;
      } else {
        return treeDigestBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    public Builder setTreeDigest(com.google.devtools.remoteexecution.v1test.Digest value) {
      if (treeDigestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        treeDigest_ = value;
        onChanged();
      } else {
        treeDigestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    public Builder setTreeDigest(
        com.google.devtools.remoteexecution.v1test.Digest.Builder builderForValue) {
      if (treeDigestBuilder_ == null) {
        treeDigest_ = builderForValue.build();
        onChanged();
      } else {
        treeDigestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    public Builder mergeTreeDigest(com.google.devtools.remoteexecution.v1test.Digest value) {
      if (treeDigestBuilder_ == null) {
        if (treeDigest_ != null) {
          treeDigest_ =
            com.google.devtools.remoteexecution.v1test.Digest.newBuilder(treeDigest_).mergeFrom(value).buildPartial();
        } else {
          treeDigest_ = value;
        }
        onChanged();
      } else {
        treeDigestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    public Builder clearTreeDigest() {
      if (treeDigestBuilder_ == null) {
        treeDigest_ = null;
        onChanged();
      } else {
        treeDigest_ = null;
        treeDigestBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    public com.google.devtools.remoteexecution.v1test.Digest.Builder getTreeDigestBuilder() {
      
      onChanged();
      return getTreeDigestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    public com.google.devtools.remoteexecution.v1test.DigestOrBuilder getTreeDigestOrBuilder() {
      if (treeDigestBuilder_ != null) {
        return treeDigestBuilder_.getMessageOrBuilder();
      } else {
        return treeDigest_ == null ?
            com.google.devtools.remoteexecution.v1test.Digest.getDefaultInstance() : treeDigest_;
      }
    }
    /**
     * <pre>
     * The digest of the encoded
     * [Tree][google.devtools.remoteexecution.v1test.Tree] proto containing the
     * directory's contents.
     * </pre>
     *
     * <code>.google.devtools.remoteexecution.v1test.Digest tree_digest = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder> 
        getTreeDigestFieldBuilder() {
      if (treeDigestBuilder_ == null) {
        treeDigestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.devtools.remoteexecution.v1test.Digest, com.google.devtools.remoteexecution.v1test.Digest.Builder, com.google.devtools.remoteexecution.v1test.DigestOrBuilder>(
                getTreeDigest(),
                getParentForChildren(),
                isClean());
        treeDigest_ = null;
      }
      return treeDigestBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.devtools.remoteexecution.v1test.OutputDirectory)
  }

  // @@protoc_insertion_point(class_scope:google.devtools.remoteexecution.v1test.OutputDirectory)
  private static final com.google.devtools.remoteexecution.v1test.OutputDirectory DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.devtools.remoteexecution.v1test.OutputDirectory();
  }

  public static com.google.devtools.remoteexecution.v1test.OutputDirectory getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OutputDirectory>
      PARSER = new com.google.protobuf.AbstractParser<OutputDirectory>() {
    @java.lang.Override
    public OutputDirectory parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OutputDirectory(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OutputDirectory> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OutputDirectory> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.devtools.remoteexecution.v1test.OutputDirectory getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

