// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface PlatformOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.Platform)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The properties that make up this platform. In order to ensure that
   * equivalent `Platform`s always hash to the same value, the properties MUST
   * be lexicographically sorted by name, and then by value. Sorting of strings
   * is done by code point, equivalently, by the UTF-8 bytes.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Platform.Property properties = 1;</code>
   */
  java.util.List<com.google.devtools.remoteexecution.v1test.Platform.Property> 
      getPropertiesList();
  /**
   * <pre>
   * The properties that make up this platform. In order to ensure that
   * equivalent `Platform`s always hash to the same value, the properties MUST
   * be lexicographically sorted by name, and then by value. Sorting of strings
   * is done by code point, equivalently, by the UTF-8 bytes.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Platform.Property properties = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.Platform.Property getProperties(int index);
  /**
   * <pre>
   * The properties that make up this platform. In order to ensure that
   * equivalent `Platform`s always hash to the same value, the properties MUST
   * be lexicographically sorted by name, and then by value. Sorting of strings
   * is done by code point, equivalently, by the UTF-8 bytes.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Platform.Property properties = 1;</code>
   */
  int getPropertiesCount();
  /**
   * <pre>
   * The properties that make up this platform. In order to ensure that
   * equivalent `Platform`s always hash to the same value, the properties MUST
   * be lexicographically sorted by name, and then by value. Sorting of strings
   * is done by code point, equivalently, by the UTF-8 bytes.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Platform.Property properties = 1;</code>
   */
  java.util.List<? extends com.google.devtools.remoteexecution.v1test.Platform.PropertyOrBuilder> 
      getPropertiesOrBuilderList();
  /**
   * <pre>
   * The properties that make up this platform. In order to ensure that
   * equivalent `Platform`s always hash to the same value, the properties MUST
   * be lexicographically sorted by name, and then by value. Sorting of strings
   * is done by code point, equivalently, by the UTF-8 bytes.
   * </pre>
   *
   * <code>repeated .google.devtools.remoteexecution.v1test.Platform.Property properties = 1;</code>
   */
  com.google.devtools.remoteexecution.v1test.Platform.PropertyOrBuilder getPropertiesOrBuilder(
      int index);
}
