// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public final class RemoteExecutionProto {
  private RemoteExecutionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_Action_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_Command_EnvironmentVariable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_Command_EnvironmentVariable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_Platform_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_Platform_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_Platform_Property_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_Platform_Property_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_Directory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_Directory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_FileNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_FileNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_DirectoryNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_DirectoryNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_Digest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_Digest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_ActionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_ActionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_OutputFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_OutputFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_Tree_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_Tree_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_ExecuteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_ExecuteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_LogFile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_LogFile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_ServerLogsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_ServerLogsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_GetActionResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_GetActionResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_UpdateActionResultRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_UpdateActionResultRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_UpdateBlobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_UpdateBlobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_GetTreeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_GetTreeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_ToolDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_ToolDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_devtools_remoteexecution_v1test_RequestMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_devtools_remoteexecution_v1test_RequestMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=google/devtools/remoteexecution/v1test" +
      "/remote_execution.proto\022&google.devtools" +
      ".remoteexecution.v1test\032\034google/api/anno" +
      "tations.proto\032#google/longrunning/operat" +
      "ions.proto\032\036google/protobuf/duration.pro" +
      "to\032\027google/rpc/status.proto\"\323\002\n\006Action\022F" +
      "\n\016command_digest\030\001 \001(\0132..google.devtools" +
      ".remoteexecution.v1test.Digest\022I\n\021input_" +
      "root_digest\030\002 \001(\0132..google.devtools.remo" +
      "teexecution.v1test.Digest\022\024\n\014output_file" +
      "s\030\003 \003(\t\022\032\n\022output_directories\030\004 \003(\t\022B\n\010p" +
      "latform\030\005 \001(\01320.google.devtools.remoteex" +
      "ecution.v1test.Platform\022*\n\007timeout\030\006 \001(\013" +
      "2\031.google.protobuf.Duration\022\024\n\014do_not_ca" +
      "che\030\007 \001(\010\"\264\001\n\007Command\022\021\n\targuments\030\001 \003(\t" +
      "\022b\n\025environment_variables\030\002 \003(\0132C.google" +
      ".devtools.remoteexecution.v1test.Command" +
      ".EnvironmentVariable\0322\n\023EnvironmentVaria" +
      "ble\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\202\001\n\010Pla" +
      "tform\022M\n\nproperties\030\001 \003(\01329.google.devto" +
      "ols.remoteexecution.v1test.Platform.Prop" +
      "erty\032\'\n\010Property\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t\"\230\001\n\tDirectory\022?\n\005files\030\001 \003(\01320.goo" +
      "gle.devtools.remoteexecution.v1test.File" +
      "Node\022J\n\013directories\030\002 \003(\01325.google.devto" +
      "ols.remoteexecution.v1test.DirectoryNode" +
      "\"o\n\010FileNode\022\014\n\004name\030\001 \001(\t\022>\n\006digest\030\002 \001" +
      "(\0132..google.devtools.remoteexecution.v1t" +
      "est.Digest\022\025\n\ris_executable\030\004 \001(\010\"]\n\rDir" +
      "ectoryNode\022\014\n\004name\030\001 \001(\t\022>\n\006digest\030\002 \001(\013" +
      "2..google.devtools.remoteexecution.v1tes" +
      "t.Digest\"*\n\006Digest\022\014\n\004hash\030\001 \001(\t\022\022\n\nsize" +
      "_bytes\030\002 \001(\003\"\366\002\n\014ActionResult\022H\n\014output_" +
      "files\030\002 \003(\01322.google.devtools.remoteexec" +
      "ution.v1test.OutputFile\022S\n\022output_direct" +
      "ories\030\003 \003(\01327.google.devtools.remoteexec" +
      "ution.v1test.OutputDirectory\022\021\n\texit_cod" +
      "e\030\004 \001(\005\022\022\n\nstdout_raw\030\005 \001(\014\022E\n\rstdout_di" +
      "gest\030\006 \001(\0132..google.devtools.remoteexecu" +
      "tion.v1test.Digest\022\022\n\nstderr_raw\030\007 \001(\014\022E" +
      "\n\rstderr_digest\030\010 \001(\0132..google.devtools." +
      "remoteexecution.v1test.Digest\"\202\001\n\nOutput" +
      "File\022\014\n\004path\030\001 \001(\t\022>\n\006digest\030\002 \001(\0132..goo" +
      "gle.devtools.remoteexecution.v1test.Dige" +
      "st\022\017\n\007content\030\003 \001(\014\022\025\n\ris_executable\030\004 \001" +
      "(\010\"\214\001\n\004Tree\022?\n\004root\030\001 \001(\01321.google.devto" +
      "ols.remoteexecution.v1test.Directory\022C\n\010" +
      "children\030\002 \003(\01321.google.devtools.remotee" +
      "xecution.v1test.Directory\"\244\001\n\017OutputDire" +
      "ctory\022\014\n\004path\030\001 \001(\t\022>\n\006digest\030\002 \001(\0132..go" +
      "ogle.devtools.remoteexecution.v1test.Dig" +
      "est\022C\n\013tree_digest\030\003 \001(\0132..google.devtoo" +
      "ls.remoteexecution.v1test.Digest\"\302\001\n\016Exe" +
      "cuteRequest\022\025\n\rinstance_name\030\001 \001(\t\022>\n\006ac" +
      "tion\030\002 \001(\0132..google.devtools.remoteexecu" +
      "tion.v1test.Action\022\031\n\021skip_cache_lookup\030" +
      "\003 \001(\010\022\036\n\026total_input_file_count\030\004 \001(\005\022\036\n" +
      "\026total_input_file_bytes\030\005 \001(\003\"a\n\007LogFile" +
      "\022>\n\006digest\030\001 \001(\0132..google.devtools.remot" +
      "eexecution.v1test.Digest\022\026\n\016human_readab" +
      "le\030\002 \001(\010\"\324\002\n\017ExecuteResponse\022D\n\006result\030\001" +
      " \001(\01324.google.devtools.remoteexecution.v" +
      "1test.ActionResult\022\025\n\rcached_result\030\002 \001(" +
      "\010\022\"\n\006status\030\003 \001(\0132\022.google.rpc.Status\022\\\n" +
      "\013server_logs\030\004 \003(\0132G.google.devtools.rem" +
      "oteexecution.v1test.ExecuteResponse.Serv" +
      "erLogsEntry\032b\n\017ServerLogsEntry\022\013\n\003key\030\001 " +
      "\001(\t\022>\n\005value\030\002 \001(\0132/.google.devtools.rem" +
      "oteexecution.v1test.LogFile:\0028\001\"\301\002\n\030Exec" +
      "uteOperationMetadata\022U\n\005stage\030\001 \001(\0162F.go" +
      "ogle.devtools.remoteexecution.v1test.Exe" +
      "cuteOperationMetadata.Stage\022E\n\raction_di" +
      "gest\030\002 \001(\0132..google.devtools.remoteexecu" +
      "tion.v1test.Digest\022\032\n\022stdout_stream_name" +
      "\030\003 \001(\t\022\032\n\022stderr_stream_name\030\004 \001(\t\"O\n\005St" +
      "age\022\013\n\007UNKNOWN\020\000\022\017\n\013CACHE_CHECK\020\001\022\n\n\006QUE" +
      "UED\020\002\022\r\n\tEXECUTING\020\003\022\r\n\tCOMPLETED\020\004\"v\n\026G" +
      "etActionResultRequest\022\025\n\rinstance_name\030\001" +
      " \001(\t\022E\n\raction_digest\030\002 \001(\0132..google.dev" +
      "tools.remoteexecution.v1test.Digest\"\306\001\n\031" +
      "UpdateActionResultRequest\022\025\n\rinstance_na" +
      "me\030\001 \001(\t\022E\n\raction_digest\030\002 \001(\0132..google" +
      ".devtools.remoteexecution.v1test.Digest\022" +
      "K\n\raction_result\030\003 \001(\01324.google.devtools" +
      ".remoteexecution.v1test.ActionResult\"v\n\027" +
      "FindMissingBlobsRequest\022\025\n\rinstance_name" +
      "\030\001 \001(\t\022D\n\014blob_digests\030\002 \003(\0132..google.de" +
      "vtools.remoteexecution.v1test.Digest\"h\n\030" +
      "FindMissingBlobsResponse\022L\n\024missing_blob" +
      "_digests\030\002 \003(\0132..google.devtools.remotee" +
      "xecution.v1test.Digest\"i\n\021UpdateBlobRequ" +
      "est\022F\n\016content_digest\030\001 \001(\0132..google.dev" +
      "tools.remoteexecution.v1test.Digest\022\014\n\004d" +
      "ata\030\002 \001(\014\"}\n\027BatchUpdateBlobsRequest\022\025\n\r" +
      "instance_name\030\001 \001(\t\022K\n\010requests\030\002 \003(\01329." +
      "google.devtools.remoteexecution.v1test.U" +
      "pdateBlobRequest\"\355\001\n\030BatchUpdateBlobsRes" +
      "ponse\022\\\n\tresponses\030\001 \003(\0132I.google.devtoo" +
      "ls.remoteexecution.v1test.BatchUpdateBlo" +
      "bsResponse.Response\032s\n\010Response\022C\n\013blob_" +
      "digest\030\001 \001(\0132..google.devtools.remoteexe" +
      "cution.v1test.Digest\022\"\n\006status\030\002 \001(\0132\022.g" +
      "oogle.rpc.Status\"\223\001\n\016GetTreeRequest\022\025\n\ri" +
      "nstance_name\030\001 \001(\t\022C\n\013root_digest\030\002 \001(\0132" +
      "..google.devtools.remoteexecution.v1test" +
      ".Digest\022\021\n\tpage_size\030\003 \001(\005\022\022\n\npage_token" +
      "\030\004 \001(\t\"r\n\017GetTreeResponse\022F\n\013directories" +
      "\030\001 \003(\01321.google.devtools.remoteexecution" +
      ".v1test.Directory\022\027\n\017next_page_token\030\002 \001" +
      "(\t\"6\n\013ToolDetails\022\021\n\ttool_name\030\001 \001(\t\022\024\n\014" +
      "tool_version\030\002 \001(\t\"\256\001\n\017RequestMetadata\022I" +
      "\n\014tool_details\030\001 \001(\01323.google.devtools.r" +
      "emoteexecution.v1test.ToolDetails\022\021\n\tact" +
      "ion_id\030\002 \001(\t\022\032\n\022tool_invocation_id\030\003 \001(\t" +
      "\022!\n\031correlated_invocations_id\030\004 \001(\t2\245\001\n\t" +
      "Execution\022\227\001\n\007Execute\0226.google.devtools." +
      "remoteexecution.v1test.ExecuteRequest\032\035." +
      "google.longrunning.Operation\"5\202\323\344\223\002/\"*/v" +
      "1test/{instance_name=**}/actions:execute" +
      ":\001*2\372\003\n\013ActionCache\022\351\001\n\017GetActionResult\022" +
      ">.google.devtools.remoteexecution.v1test" +
      ".GetActionResultRequest\0324.google.devtool" +
      "s.remoteexecution.v1test.ActionResult\"`\202" +
      "\323\344\223\002Z\022X/v1test/{instance_name=**}/action" +
      "Results/{action_digest.hash}/{action_dig" +
      "est.size_bytes}\022\376\001\n\022UpdateActionResult\022A" +
      ".google.devtools.remoteexecution.v1test." +
      "UpdateActionResultRequest\0324.google.devto" +
      "ols.remoteexecution.v1test.ActionResult\"" +
      "o\202\323\344\223\002i\032X/v1test/{instance_name=**}/acti" +
      "onResults/{action_digest.hash}/{action_d" +
      "igest.size_bytes}:\raction_result2\230\005\n\031Con" +
      "tentAddressableStorage\022\316\001\n\020FindMissingBl" +
      "obs\022?.google.devtools.remoteexecution.v1" +
      "test.FindMissingBlobsRequest\032@.google.de" +
      "vtools.remoteexecution.v1test.FindMissin" +
      "gBlobsResponse\"7\202\323\344\223\0021\",/v1test/{instanc" +
      "e_name=**}/blobs:findMissing:\001*\022\316\001\n\020Batc" +
      "hUpdateBlobs\022?.google.devtools.remoteexe" +
      "cution.v1test.BatchUpdateBlobsRequest\032@." +
      "google.devtools.remoteexecution.v1test.B" +
      "atchUpdateBlobsResponse\"7\202\323\344\223\0021\",/v1test" +
      "/{instance_name=**}/blobs:batchUpdate:\001*" +
      "\022\330\001\n\007GetTree\0226.google.devtools.remoteexe" +
      "cution.v1test.GetTreeRequest\0327.google.de" +
      "vtools.remoteexecution.v1test.GetTreeRes" +
      "ponse\"\\\202\323\344\223\002V\022T/v1test/{instance_name=**" +
      "}/blobs/{root_digest.hash}/{root_digest." +
      "size_bytes}:getTreeB\301\001\n*com.google.devto" +
      "ols.remoteexecution.v1testB\024RemoteExecut" +
      "ionProtoP\001ZUgoogle.golang.org/genproto/g" +
      "oogleapis/devtools/remoteexecution/v1tes" +
      "t;remoteexecution\242\002\003REX\252\002\035Google.RemoteE" +
      "xecution.V1Testb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.longrunning.OperationsProto.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        }, assigner);
    internal_static_google_devtools_remoteexecution_v1test_Action_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_devtools_remoteexecution_v1test_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_Action_descriptor,
        new java.lang.String[] { "CommandDigest", "InputRootDigest", "OutputFiles", "OutputDirectories", "Platform", "Timeout", "DoNotCache", });
    internal_static_google_devtools_remoteexecution_v1test_Command_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_devtools_remoteexecution_v1test_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_Command_descriptor,
        new java.lang.String[] { "Arguments", "EnvironmentVariables", });
    internal_static_google_devtools_remoteexecution_v1test_Command_EnvironmentVariable_descriptor =
      internal_static_google_devtools_remoteexecution_v1test_Command_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_remoteexecution_v1test_Command_EnvironmentVariable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_Command_EnvironmentVariable_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_google_devtools_remoteexecution_v1test_Platform_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_devtools_remoteexecution_v1test_Platform_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_Platform_descriptor,
        new java.lang.String[] { "Properties", });
    internal_static_google_devtools_remoteexecution_v1test_Platform_Property_descriptor =
      internal_static_google_devtools_remoteexecution_v1test_Platform_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_remoteexecution_v1test_Platform_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_Platform_Property_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_google_devtools_remoteexecution_v1test_Directory_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_devtools_remoteexecution_v1test_Directory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_Directory_descriptor,
        new java.lang.String[] { "Files", "Directories", });
    internal_static_google_devtools_remoteexecution_v1test_FileNode_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_devtools_remoteexecution_v1test_FileNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_FileNode_descriptor,
        new java.lang.String[] { "Name", "Digest", "IsExecutable", });
    internal_static_google_devtools_remoteexecution_v1test_DirectoryNode_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_devtools_remoteexecution_v1test_DirectoryNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_DirectoryNode_descriptor,
        new java.lang.String[] { "Name", "Digest", });
    internal_static_google_devtools_remoteexecution_v1test_Digest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_devtools_remoteexecution_v1test_Digest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_Digest_descriptor,
        new java.lang.String[] { "Hash", "SizeBytes", });
    internal_static_google_devtools_remoteexecution_v1test_ActionResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_devtools_remoteexecution_v1test_ActionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_ActionResult_descriptor,
        new java.lang.String[] { "OutputFiles", "OutputDirectories", "ExitCode", "StdoutRaw", "StdoutDigest", "StderrRaw", "StderrDigest", });
    internal_static_google_devtools_remoteexecution_v1test_OutputFile_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_devtools_remoteexecution_v1test_OutputFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_OutputFile_descriptor,
        new java.lang.String[] { "Path", "Digest", "Content", "IsExecutable", });
    internal_static_google_devtools_remoteexecution_v1test_Tree_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_google_devtools_remoteexecution_v1test_Tree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_Tree_descriptor,
        new java.lang.String[] { "Root", "Children", });
    internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_OutputDirectory_descriptor,
        new java.lang.String[] { "Path", "Digest", "TreeDigest", });
    internal_static_google_devtools_remoteexecution_v1test_ExecuteRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_google_devtools_remoteexecution_v1test_ExecuteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_ExecuteRequest_descriptor,
        new java.lang.String[] { "InstanceName", "Action", "SkipCacheLookup", "TotalInputFileCount", "TotalInputFileBytes", });
    internal_static_google_devtools_remoteexecution_v1test_LogFile_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_google_devtools_remoteexecution_v1test_LogFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_LogFile_descriptor,
        new java.lang.String[] { "Digest", "HumanReadable", });
    internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_descriptor,
        new java.lang.String[] { "Result", "CachedResult", "Status", "ServerLogs", });
    internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_ServerLogsEntry_descriptor =
      internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_ServerLogsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_ExecuteResponse_ServerLogsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_ExecuteOperationMetadata_descriptor,
        new java.lang.String[] { "Stage", "ActionDigest", "StdoutStreamName", "StderrStreamName", });
    internal_static_google_devtools_remoteexecution_v1test_GetActionResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_google_devtools_remoteexecution_v1test_GetActionResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_GetActionResultRequest_descriptor,
        new java.lang.String[] { "InstanceName", "ActionDigest", });
    internal_static_google_devtools_remoteexecution_v1test_UpdateActionResultRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_google_devtools_remoteexecution_v1test_UpdateActionResultRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_UpdateActionResultRequest_descriptor,
        new java.lang.String[] { "InstanceName", "ActionDigest", "ActionResult", });
    internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsRequest_descriptor,
        new java.lang.String[] { "InstanceName", "BlobDigests", });
    internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_FindMissingBlobsResponse_descriptor,
        new java.lang.String[] { "MissingBlobDigests", });
    internal_static_google_devtools_remoteexecution_v1test_UpdateBlobRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_google_devtools_remoteexecution_v1test_UpdateBlobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_UpdateBlobRequest_descriptor,
        new java.lang.String[] { "ContentDigest", "Data", });
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsRequest_descriptor,
        new java.lang.String[] { "InstanceName", "Requests", });
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_descriptor,
        new java.lang.String[] { "Responses", });
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_Response_descriptor =
      internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_descriptor.getNestedTypes().get(0);
    internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_BatchUpdateBlobsResponse_Response_descriptor,
        new java.lang.String[] { "BlobDigest", "Status", });
    internal_static_google_devtools_remoteexecution_v1test_GetTreeRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_google_devtools_remoteexecution_v1test_GetTreeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_GetTreeRequest_descriptor,
        new java.lang.String[] { "InstanceName", "RootDigest", "PageSize", "PageToken", });
    internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_GetTreeResponse_descriptor,
        new java.lang.String[] { "Directories", "NextPageToken", });
    internal_static_google_devtools_remoteexecution_v1test_ToolDetails_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_google_devtools_remoteexecution_v1test_ToolDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_ToolDetails_descriptor,
        new java.lang.String[] { "ToolName", "ToolVersion", });
    internal_static_google_devtools_remoteexecution_v1test_RequestMetadata_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_google_devtools_remoteexecution_v1test_RequestMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_devtools_remoteexecution_v1test_RequestMetadata_descriptor,
        new java.lang.String[] { "ToolDetails", "ActionId", "ToolInvocationId", "CorrelatedInvocationsId", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
