// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/devtools/remoteexecution/v1test/remote_execution.proto

package com.google.devtools.remoteexecution.v1test;

public interface UpdateActionResultRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.devtools.remoteexecution.v1test.UpdateActionResultRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The instance of the execution system to operate against. A server may
   * support multiple instances of the execution system (with their own workers,
   * storage, caches, etc.). The server MAY require use of this field to select
   * between them in an implementation-defined fashion, otherwise it can be
   * omitted.
   * </pre>
   *
   * <code>string instance_name = 1;</code>
   */
  java.lang.String getInstanceName();
  /**
   * <pre>
   * The instance of the execution system to operate against. A server may
   * support multiple instances of the execution system (with their own workers,
   * storage, caches, etc.). The server MAY require use of this field to select
   * between them in an implementation-defined fashion, otherwise it can be
   * omitted.
   * </pre>
   *
   * <code>string instance_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getInstanceNameBytes();

  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * whose result is being uploaded.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   */
  boolean hasActionDigest();
  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * whose result is being uploaded.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.Digest getActionDigest();
  /**
   * <pre>
   * The digest of the [Action][google.devtools.remoteexecution.v1test.Action]
   * whose result is being uploaded.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.Digest action_digest = 2;</code>
   */
  com.google.devtools.remoteexecution.v1test.DigestOrBuilder getActionDigestOrBuilder();

  /**
   * <pre>
   * The [ActionResult][google.devtools.remoteexecution.v1test.ActionResult]
   * to store in the cache.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.ActionResult action_result = 3;</code>
   */
  boolean hasActionResult();
  /**
   * <pre>
   * The [ActionResult][google.devtools.remoteexecution.v1test.ActionResult]
   * to store in the cache.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.ActionResult action_result = 3;</code>
   */
  com.google.devtools.remoteexecution.v1test.ActionResult getActionResult();
  /**
   * <pre>
   * The [ActionResult][google.devtools.remoteexecution.v1test.ActionResult]
   * to store in the cache.
   * </pre>
   *
   * <code>.google.devtools.remoteexecution.v1test.ActionResult action_result = 3;</code>
   */
  com.google.devtools.remoteexecution.v1test.ActionResultOrBuilder getActionResultOrBuilder();
}
